<?php

declare(strict_types=1);

namespace DRESearch\View;

use Laminas\View\Renderer\PhpRenderer;

/**
 * Hands the Svelte client its UI strings in the site's language.
 *
 * The client ships English (src/svelte/lib/i18n.ts) and reads overrides from
 * `window.dreSearchTranslations` when its chunk loads. This translates every
 * client string through Omeka's translator (language/<locale>.mo, built from
 * language/template.pot) and emits only those that differ — an English site
 * gets no extra script at all. Emitted once per page however many search
 * surfaces it carries.
 */
final class ClientStrings
{
    private static bool $injected = false;

    public static function inject(PhpRenderer $view): void
    {
        if (self::$injected) {
            return;
        }
        self::$injected = true;
        $translated = [];
        foreach (self::table() as $key => $english) {
            $value = (string) $view->translate($english);
            if ($value !== $english && $value !== '') {
                $translated[$key] = $value;
            }
        }
        if ($translated === []) {
            return;
        }
        $json = json_encode(
            $translated,
            JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP
                | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_INVALID_UTF8_SUBSTITUTE,
        );
        if ($json !== false) {
            $view->headScript()->appendScript('window.dreSearchTranslations = ' . $json . ';');
        }
    }

    /** @return array<string,string> key => English (generated by scripts/build-translations.php) */
    public static function table(): array
    {
        static $table = null;
        if ($table === null) {
            $raw = @file_get_contents(dirname(__DIR__, 2) . '/data/client-strings.json');
            $decoded = is_string($raw) ? json_decode($raw, true) : null;
            $table = is_array($decoded) ? array_filter($decoded, 'is_string') : [];
        }
        return $table;
    }

    /** For tests: allow a second injection in the same process. */
    public static function reset(): void
    {
        self::$injected = false;
    }
}
